services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: Joy
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: ecc
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./backend/db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  app_network:
    driver: bridge
